<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit888d1a0b29508e90db441c953a6e756b
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Curl\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Curl\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-curl-class/php-curl-class/src/Curl',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit888d1a0b29508e90db441c953a6e756b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit888d1a0b29508e90db441c953a6e756b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
